---
extends: default

ignore: |
  compose/sops-secrets.yaml
  crowdsec/notifications/ha-webhook.yaml

rules:
  document-start: disable
  line-length:
    max: 160
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
