---
default_config:

homeassistant:
  name: Home
  unit_system: metric
  time_zone: America/Sao_Paulo
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation

recorder:
  db_url: !secret recorder_db_url

automation: !include automations.yaml
script: !include scripts.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.19.0.0/16